"""
Ahmedabad Geospatial Datasets for Python Backend
"""

AHMEDABAD_WARDS_DATA = [
    {
        "id": "isanpur",
        "name": "Isanpur",
        "name_gu": "ઇસનપુર",
        "name_hi": "ईसनपुर",
        "zone": "South",
        "lat": 22.9774,
        "lng": 72.5938,
        "population_density": 24500,
        "residential_density": 92,
        "poi_count": {"schools": 14, "markets": 3, "brts": 4, "metro": 1, "hospitals": 5, "temples": 8},
        "footfall_index": 88,
        "best_window": "5:00 PM – 8:00 PM",
    },
    {
        "id": "maninagar",
        "name": "Maninagar",
        "name_gu": "મણિનગર",
        "name_hi": "मणिनगर",
        "zone": "South",
        "lat": 22.9984,
        "lng": 72.6027,
        "population_density": 28000,
        "residential_density": 94,
        "poi_count": {"schools": 22, "markets": 6, "brts": 6, "metro": 2, "hospitals": 9, "temples": 12},
        "footfall_index": 94,
        "best_window": "4:30 PM – 8:30 PM",
    },
    {
        "id": "lambha",
        "name": "Lambha",
        "name_gu": "લાંભા",
        "name_hi": "लांभा",
        "zone": "South",
        "lat": 22.9463,
        "lng": 72.5852,
        "population_density": 16800,
        "residential_density": 84,
        "poi_count": {"schools": 9, "markets": 2, "brts": 2, "metro": 0, "hospitals": 3, "temples": 6},
        "footfall_index": 79,
        "best_window": "4:00 PM – 7:30 PM",
    },
    {
        "id": "ramol",
        "name": "Ramol",
        "name_gu": "રામોલ",
        "name_hi": "रामोल",
        "zone": "East",
        "lat": 22.9867,
        "lng": 72.6481,
        "population_density": 19200,
        "residential_density": 86,
        "poi_count": {"schools": 11, "markets": 3, "brts": 3, "metro": 1, "hospitals": 4, "temples": 7},
        "footfall_index": 77,
        "best_window": "5:00 PM – 8:00 PM",
    },
    {
        "id": "vastrapur",
        "name": "Vastrapur",
        "name_gu": "વસ્ત્રાપુર",
        "name_hi": "वस्त्रापुर",
        "zone": "West",
        "lat": 23.0350,
        "lng": 72.5293,
        "population_density": 21000,
        "residential_density": 89,
        "poi_count": {"schools": 16, "markets": 5, "brts": 5, "metro": 2, "hospitals": 7, "temples": 5},
        "footfall_index": 92,
        "best_window": "7:30 AM – 11:00 AM & 5:00 PM – 8:30 PM",
    },
]

PRODUCE_CATALOG = [
    {"id": "tomato", "name": "Tomato", "name_gu": "ટામેટા", "name_hi": "टमाटर", "icon": "🍅", "category": "vegetables", "wholesale": 18, "retail": 35, "share": 0.20, "demand": 1.35},
    {"id": "potato", "name": "Potato", "name_gu": "બટાકા", "name_hi": "आलू", "icon": "🥔", "category": "vegetables", "wholesale": 16, "retail": 28, "share": 0.175, "demand": 1.40},
    {"id": "onion", "name": "Onion", "name_gu": "ડુંગળી", "name_hi": "प्याज", "icon": "🧅", "category": "vegetables", "wholesale": 22, "retail": 38, "share": 0.15, "demand": 1.30},
    {"id": "banana", "name": "Banana", "name_gu": "કેળા", "name_hi": "केला", "icon": "🍌", "category": "fruits", "wholesale": 25, "retail": 45, "share": 0.15, "demand": 1.25},
    {"id": "coriander", "name": "Coriander", "name_gu": "કોથમીર", "name_hi": "धनिया", "icon": "🌿", "category": "leafy", "wholesale": 30, "retail": 70, "share": 0.075, "demand": 1.50},
    {"id": "green_chili", "name": "Green Chili", "name_gu": "લીલા મરચાં", "name_hi": "हरी मिर्च", "icon": "🌶️", "category": "vegetables", "wholesale": 40, "retail": 80, "share": 0.05, "demand": 1.20},
]
